// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/userapi/user.proto

/*
Package userapi is a generated protocol buffer package.

It is generated from these files:
	pkg/userapi/user.proto

It has these top-level messages:
*/
package userapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

// Server API for User service

type UserServer interface {
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userapi.User",
	HandlerType: (*UserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/userapi/user.proto",
}

func init() { proto.RegisterFile("pkg/userapi/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 61 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xc8, 0x4e, 0xd7,
	0x2f, 0x2d, 0x4e, 0x2d, 0x4a, 0x2c, 0xc8, 0x04, 0xd3, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0xec, 0x50, 0x31, 0x23, 0x36, 0x2e, 0x96, 0xd0, 0xe2, 0xd4, 0xa2, 0x24, 0x36, 0xb0, 0xb8, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x8b, 0x02, 0x32, 0x31, 0x00, 0x00, 0x00,
}
