#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd ${DIR} > /dev/null 2>&1
go-bindata -o migrations.go -pkg migrations -prefix 'sql/' sql/
goimports -w migrations.go
popd > /dev/null 2>&1
